// flow-typed signature: 800e0f7bf2c5a858d5c7524f104eb613
// flow-typed version: <<STUB>>/console-stamp_v0.2.6/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'console-stamp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'console-stamp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'console-stamp/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'console-stamp/main.js' {
  declare module.exports: $Exports<'console-stamp/main'>;
}
